# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-performance
  - rubocop-erb
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/ExampleLength:
  Max: 12

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 6
