SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tiger; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tiger;


--
-- Name: topology; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA topology;


--
-- Name: SCHEMA topology; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA topology IS 'PostGIS Topology schema';


--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


--
-- Name: fuzzystrmatch; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS fuzzystrmatch WITH SCHEMA public;


--
-- Name: EXTENSION fuzzystrmatch; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION fuzzystrmatch IS 'determine similarities and distance between strings';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: postgis_tiger_geocoder; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder WITH SCHEMA tiger;


--
-- Name: EXTENSION postgis_tiger_geocoder; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis_tiger_geocoder IS 'PostGIS tiger geocoder and reverse geocoder';


--
-- Name: postgis_topology; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;


--
-- Name: EXTENSION postgis_topology; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis_topology IS 'PostGIS topology spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: active_storage_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.active_storage_attachments (
    id bigint NOT NULL,
    name text NOT NULL,
    record_type text NOT NULL,
    record_id bigint NOT NULL,
    blob_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: active_storage_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.active_storage_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.active_storage_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: active_storage_blobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.active_storage_blobs (
    id bigint NOT NULL,
    key text NOT NULL,
    filename text NOT NULL,
    content_type text,
    metadata text,
    service_name text NOT NULL,
    byte_size bigint NOT NULL,
    checksum text,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: active_storage_blobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.active_storage_blobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.active_storage_blobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: airports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.airports (
    place_id uuid NOT NULL,
    operational_status text NOT NULL,
    iata_code text,
    icao_code text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: ar_internal_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ar_internal_metadata (
    key character varying NOT NULL,
    value character varying,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: import_airport_source_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_airport_source_links (
    id bigint NOT NULL,
    source_record_id bigint NOT NULL,
    airport_place_id uuid NOT NULL,
    match_strategy text NOT NULL,
    confidence numeric(5,4) NOT NULL,
    matched_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: import_airport_source_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_airport_source_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_airport_source_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_artifacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_artifacts (
    id bigint NOT NULL,
    run_id bigint NOT NULL,
    run_item_id bigint,
    kind text NOT NULL,
    sha256 text NOT NULL,
    byte_size bigint,
    content_type text,
    source_url text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: import_artifacts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_artifacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_artifacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_issues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_issues (
    id bigint NOT NULL,
    run_id bigint NOT NULL,
    run_item_id bigint,
    source_record_id bigint,
    stage text NOT NULL,
    code text NOT NULL,
    severity text NOT NULL,
    status text NOT NULL,
    message text NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    row_locator text,
    resolved_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: import_issues_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_issues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_issues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_record_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_record_snapshots (
    id bigint NOT NULL,
    source_record_id bigint NOT NULL,
    run_id bigint NOT NULL,
    checksum text NOT NULL,
    raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    normalized_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: import_record_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_record_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_record_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_run_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_run_items (
    id bigint NOT NULL,
    run_id bigint NOT NULL,
    item_kind text NOT NULL,
    item_key text NOT NULL,
    status text NOT NULL,
    params jsonb DEFAULT '{}'::jsonb NOT NULL,
    checkpoint jsonb DEFAULT '{}'::jsonb NOT NULL,
    stats jsonb DEFAULT '{}'::jsonb NOT NULL,
    attempts_count integer DEFAULT 0 NOT NULL,
    lease_token text,
    lease_expires_at timestamp with time zone,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    error_code text,
    error_message text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: import_run_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_run_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_run_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_runs (
    id bigint NOT NULL,
    source_id bigint NOT NULL,
    retry_of_run_id bigint,
    initiated_by_user_id uuid,
    mode text NOT NULL,
    status text NOT NULL,
    params jsonb DEFAULT '{}'::jsonb NOT NULL,
    stats jsonb DEFAULT '{}'::jsonb NOT NULL,
    total_item_count integer DEFAULT 0 NOT NULL,
    completed_item_count integer DEFAULT 0 NOT NULL,
    failed_item_count integer DEFAULT 0 NOT NULL,
    issue_count integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    cancel_requested_at timestamp with time zone,
    error_code text,
    error_message text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: import_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_source_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_source_records (
    id bigint NOT NULL,
    source_id bigint NOT NULL,
    record_kind text NOT NULL,
    external_uid text NOT NULL,
    status text NOT NULL,
    checksum text NOT NULL,
    raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    normalized_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    last_changed_at timestamp with time zone,
    last_import_run_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: import_source_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_source_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_source_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_sources (
    id bigint NOT NULL,
    key text NOT NULL,
    provider_key text NOT NULL,
    dataset_key text NOT NULL,
    target_kind text NOT NULL,
    fetch_mode text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    license_key text NOT NULL,
    license_url text,
    attribution_text text,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: import_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_names; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place_names (
    id uuid DEFAULT uuidv7() NOT NULL,
    place_id uuid NOT NULL,
    locale text NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: places; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.places (
    id uuid DEFAULT uuidv7() NOT NULL,
    kind text NOT NULL,
    name text NOT NULL,
    municipality_name text,
    country_code text NOT NULL,
    region_code text,
    continent_code text,
    location public.geography(Point,4326) NOT NULL,
    time_zone text,
    time_zone_source text,
    time_zone_verified_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: user_identities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_identities (
    id uuid DEFAULT uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    provider text NOT NULL,
    provider_uid text,
    email public.citext,
    email_verified boolean DEFAULT false NOT NULL,
    password_digest text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    password_reset_token_digest text,
    password_reset_sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sessions (
    id uuid DEFAULT uuidv7() NOT NULL,
    user_id uuid NOT NULL,
    user_identity_id uuid NOT NULL,
    authentication_method text NOT NULL,
    token_digest text NOT NULL,
    ip_address inet,
    user_agent text,
    last_seen_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT uuidv7() NOT NULL,
    primary_email public.citext NOT NULL,
    primary_email_verified_at timestamp with time zone,
    role text DEFAULT 'member'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    display_name text,
    locale text DEFAULT 'en'::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: active_storage_attachments active_storage_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_storage_attachments
    ADD CONSTRAINT active_storage_attachments_pkey PRIMARY KEY (id);


--
-- Name: active_storage_attachments active_storage_attachments_uniqueness; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_storage_attachments
    ADD CONSTRAINT active_storage_attachments_uniqueness UNIQUE (record_type, record_id, name);


--
-- Name: active_storage_blobs active_storage_blobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_storage_blobs
    ADD CONSTRAINT active_storage_blobs_pkey PRIMARY KEY (id);


--
-- Name: airports airports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.airports
    ADD CONSTRAINT airports_pkey PRIMARY KEY (place_id);


--
-- Name: ar_internal_metadata ar_internal_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ar_internal_metadata
    ADD CONSTRAINT ar_internal_metadata_pkey PRIMARY KEY (key);


--
-- Name: import_airport_source_links import_airport_source_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_airport_source_links
    ADD CONSTRAINT import_airport_source_links_pkey PRIMARY KEY (id);


--
-- Name: import_artifacts import_artifacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_artifacts
    ADD CONSTRAINT import_artifacts_pkey PRIMARY KEY (id);


--
-- Name: import_issues import_issues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_issues
    ADD CONSTRAINT import_issues_pkey PRIMARY KEY (id);


--
-- Name: import_record_snapshots import_record_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_record_snapshots
    ADD CONSTRAINT import_record_snapshots_pkey PRIMARY KEY (id);


--
-- Name: import_run_items import_run_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_run_items
    ADD CONSTRAINT import_run_items_pkey PRIMARY KEY (id);


--
-- Name: import_runs import_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_runs
    ADD CONSTRAINT import_runs_pkey PRIMARY KEY (id);


--
-- Name: import_source_records import_source_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_source_records
    ADD CONSTRAINT import_source_records_pkey PRIMARY KEY (id);


--
-- Name: import_sources import_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_sources
    ADD CONSTRAINT import_sources_pkey PRIMARY KEY (id);


--
-- Name: place_names place_names_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_names
    ADD CONSTRAINT place_names_pkey PRIMARY KEY (id);


--
-- Name: place_names place_names_place_id_locale_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_names
    ADD CONSTRAINT place_names_place_id_locale_key UNIQUE (place_id, locale);


--
-- Name: places places_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: user_identities user_identities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_identities
    ADD CONSTRAINT user_identities_pkey PRIMARY KEY (id);


--
-- Name: user_sessions user_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: index_active_storage_attachments_on_blob_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_active_storage_attachments_on_blob_id ON public.active_storage_attachments USING btree (blob_id);


--
-- Name: index_active_storage_blobs_on_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_active_storage_blobs_on_key ON public.active_storage_blobs USING btree (key);


--
-- Name: index_airports_on_iata_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_airports_on_iata_code ON public.airports USING btree (iata_code) WHERE (iata_code IS NOT NULL);


--
-- Name: index_airports_on_icao_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_airports_on_icao_code ON public.airports USING btree (icao_code) WHERE (icao_code IS NOT NULL);


--
-- Name: index_import_airport_source_links_on_airport_place_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_airport_source_links_on_airport_place_id ON public.import_airport_source_links USING btree (airport_place_id);


--
-- Name: index_import_airport_source_links_on_source_record_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_airport_source_links_on_source_record_id ON public.import_airport_source_links USING btree (source_record_id);


--
-- Name: index_import_artifacts_on_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_artifacts_on_run_id ON public.import_artifacts USING btree (run_id);


--
-- Name: index_import_artifacts_on_run_item_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_artifacts_on_run_item_id ON public.import_artifacts USING btree (run_item_id);


--
-- Name: index_import_artifacts_on_sha256; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_artifacts_on_sha256 ON public.import_artifacts USING btree (sha256);


--
-- Name: index_import_issues_on_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_issues_on_run_id ON public.import_issues USING btree (run_id);


--
-- Name: index_import_issues_on_run_item_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_issues_on_run_item_id ON public.import_issues USING btree (run_item_id);


--
-- Name: index_import_issues_on_source_record_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_issues_on_source_record_id ON public.import_issues USING btree (source_record_id);


--
-- Name: index_import_issues_on_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_issues_on_status ON public.import_issues USING btree (status);


--
-- Name: index_import_record_snapshots_on_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_record_snapshots_on_run_id ON public.import_record_snapshots USING btree (run_id);


--
-- Name: index_import_record_snapshots_on_source_record_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_record_snapshots_on_source_record_id ON public.import_record_snapshots USING btree (source_record_id);


--
-- Name: index_import_run_items_on_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_run_items_on_run_id ON public.import_run_items USING btree (run_id);


--
-- Name: index_import_run_items_on_run_kind_and_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_run_items_on_run_kind_and_key ON public.import_run_items USING btree (run_id, item_kind, item_key);


--
-- Name: index_import_run_items_on_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_run_items_on_status ON public.import_run_items USING btree (status);


--
-- Name: index_import_runs_on_retry_of_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_runs_on_retry_of_run_id ON public.import_runs USING btree (retry_of_run_id);


--
-- Name: index_import_runs_on_source_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_runs_on_source_id ON public.import_runs USING btree (source_id);


--
-- Name: index_import_runs_on_source_id_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_runs_on_source_id_active ON public.import_runs USING btree (source_id) WHERE (status = ANY (ARRAY['queued'::text, 'running'::text]));


--
-- Name: index_import_source_records_on_identity; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_source_records_on_identity ON public.import_source_records USING btree (source_id, record_kind, external_uid);


--
-- Name: index_import_source_records_on_last_import_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_source_records_on_last_import_run_id ON public.import_source_records USING btree (last_import_run_id);


--
-- Name: index_import_source_records_on_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_import_source_records_on_status ON public.import_source_records USING btree (status);


--
-- Name: index_import_sources_on_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_import_sources_on_key ON public.import_sources USING btree (key);


--
-- Name: index_place_names_on_place_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_place_names_on_place_id ON public.place_names USING btree (place_id);


--
-- Name: index_places_on_country_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_places_on_country_code ON public.places USING btree (country_code);


--
-- Name: index_places_on_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_places_on_location ON public.places USING gist (location);


--
-- Name: index_user_identities_on_password_reset_token_digest; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_user_identities_on_password_reset_token_digest ON public.user_identities USING btree (password_reset_token_digest) WHERE (password_reset_token_digest IS NOT NULL);


--
-- Name: index_user_identities_on_provider_and_provider_uid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_user_identities_on_provider_and_provider_uid ON public.user_identities USING btree (provider, provider_uid) WHERE (provider_uid IS NOT NULL);


--
-- Name: index_user_identities_on_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_user_identities_on_user_id ON public.user_identities USING btree (user_id);


--
-- Name: index_user_identities_on_user_id_and_provider_for_password; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_user_identities_on_user_id_and_provider_for_password ON public.user_identities USING btree (user_id, provider) WHERE (provider = 'password'::text);


--
-- Name: index_user_sessions_on_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_user_sessions_on_expires_at ON public.user_sessions USING btree (expires_at);


--
-- Name: index_user_sessions_on_revoked_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_user_sessions_on_revoked_at ON public.user_sessions USING btree (revoked_at);


--
-- Name: index_user_sessions_on_token_digest; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_user_sessions_on_token_digest ON public.user_sessions USING btree (token_digest);


--
-- Name: index_user_sessions_on_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_user_sessions_on_user_id ON public.user_sessions USING btree (user_id);


--
-- Name: index_user_sessions_on_user_identity_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_user_sessions_on_user_identity_id ON public.user_sessions USING btree (user_identity_id);


--
-- Name: index_users_on_primary_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_users_on_primary_email ON public.users USING btree (primary_email);


--
-- Name: active_storage_attachments active_storage_attachments_blob_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_storage_attachments
    ADD CONSTRAINT active_storage_attachments_blob_id_fkey FOREIGN KEY (blob_id) REFERENCES public.active_storage_blobs(id);


--
-- Name: airports airports_place_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.airports
    ADD CONSTRAINT airports_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.places(id) ON DELETE CASCADE;


--
-- Name: import_airport_source_links import_airport_source_links_airport_place_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_airport_source_links
    ADD CONSTRAINT import_airport_source_links_airport_place_id_fkey FOREIGN KEY (airport_place_id) REFERENCES public.airports(place_id);


--
-- Name: import_airport_source_links import_airport_source_links_source_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_airport_source_links
    ADD CONSTRAINT import_airport_source_links_source_record_id_fkey FOREIGN KEY (source_record_id) REFERENCES public.import_source_records(id);


--
-- Name: import_artifacts import_artifacts_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_artifacts
    ADD CONSTRAINT import_artifacts_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.import_runs(id);


--
-- Name: import_artifacts import_artifacts_run_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_artifacts
    ADD CONSTRAINT import_artifacts_run_item_id_fkey FOREIGN KEY (run_item_id) REFERENCES public.import_run_items(id) ON DELETE SET NULL;


--
-- Name: import_issues import_issues_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_issues
    ADD CONSTRAINT import_issues_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.import_runs(id);


--
-- Name: import_issues import_issues_run_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_issues
    ADD CONSTRAINT import_issues_run_item_id_fkey FOREIGN KEY (run_item_id) REFERENCES public.import_run_items(id) ON DELETE SET NULL;


--
-- Name: import_issues import_issues_source_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_issues
    ADD CONSTRAINT import_issues_source_record_id_fkey FOREIGN KEY (source_record_id) REFERENCES public.import_source_records(id) ON DELETE SET NULL;


--
-- Name: import_record_snapshots import_record_snapshots_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_record_snapshots
    ADD CONSTRAINT import_record_snapshots_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.import_runs(id);


--
-- Name: import_record_snapshots import_record_snapshots_source_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_record_snapshots
    ADD CONSTRAINT import_record_snapshots_source_record_id_fkey FOREIGN KEY (source_record_id) REFERENCES public.import_source_records(id);


--
-- Name: import_run_items import_run_items_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_run_items
    ADD CONSTRAINT import_run_items_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.import_runs(id);


--
-- Name: import_runs import_runs_initiated_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_runs
    ADD CONSTRAINT import_runs_initiated_by_user_id_fkey FOREIGN KEY (initiated_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: import_runs import_runs_retry_of_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_runs
    ADD CONSTRAINT import_runs_retry_of_run_id_fkey FOREIGN KEY (retry_of_run_id) REFERENCES public.import_runs(id);


--
-- Name: import_runs import_runs_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_runs
    ADD CONSTRAINT import_runs_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.import_sources(id);


--
-- Name: import_source_records import_source_records_last_import_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_source_records
    ADD CONSTRAINT import_source_records_last_import_run_id_fkey FOREIGN KEY (last_import_run_id) REFERENCES public.import_runs(id) ON DELETE SET NULL;


--
-- Name: import_source_records import_source_records_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_source_records
    ADD CONSTRAINT import_source_records_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.import_sources(id);


--
-- Name: place_names place_names_place_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_names
    ADD CONSTRAINT place_names_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.places(id) ON DELETE CASCADE;


--
-- Name: user_identities user_identities_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_identities
    ADD CONSTRAINT user_identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_sessions user_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_sessions user_sessions_user_identity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_user_identity_id_fkey FOREIGN KEY (user_identity_id) REFERENCES public.user_identities(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

SET search_path TO "$user", public, topology, tiger;

INSERT INTO "schema_migrations" (version) VALUES
('20260710130000'),
('20260710100000'),
('20260708132000'),
('20260707000100');

