class AddCountryReferenceCatalog < ActiveRecord::Migration[8.1]
  def up
    execute <<~SQL
      CREATE TABLE countries (
        id uuid PRIMARY KEY DEFAULT uuidv7(),
        code text NOT NULL,
        name text NOT NULL,
        continent_code text NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_countries_on_code
      ON countries (code);
    SQL

    execute <<~SQL
      CREATE TABLE country_names (
        id uuid PRIMARY KEY DEFAULT uuidv7(),
        country_id uuid NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
        locale text NOT NULL,
        name text NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT country_names_country_id_locale_key UNIQUE (country_id, locale)
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_country_names_on_country_id
      ON country_names (country_id);
    SQL

    execute <<~SQL
      ALTER TABLE places
      ADD COLUMN country_id uuid REFERENCES countries(id);
    SQL

    execute <<~SQL
      CREATE INDEX index_places_on_country_id
      ON places (country_id);
    SQL

    execute <<~SQL
      CREATE TABLE import_country_source_links (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_record_id bigint NOT NULL REFERENCES import_source_records(id),
        country_id uuid NOT NULL REFERENCES countries(id),
        matched_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_country_source_links_on_source_record_id
      ON import_country_source_links (source_record_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_country_source_links_on_country_id
      ON import_country_source_links (country_id);
    SQL

    execute <<~SQL
      CREATE TABLE import_country_name_source_links (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_record_id bigint NOT NULL REFERENCES import_source_records(id),
        country_name_id uuid NOT NULL REFERENCES country_names(id),
        matched_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_country_name_links_on_source_record_id
      ON import_country_name_source_links (source_record_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_country_name_links_on_country_name_id
      ON import_country_name_source_links (country_name_id);
    SQL

    execute <<~SQL
      INSERT INTO import_sources (
        key,
        provider_key,
        dataset_key,
        target_kind,
        fetch_mode,
        license_key,
        attribution_text
      ) VALUES
        (
          'country_catalog',
          'routeprint',
          'country_catalog',
          'country',
          'remote_dump',
          'multiple',
          'OurAirports (Public Domain); Unicode CLDR (Unicode License v3)'
        ) ON CONFLICT (key) DO NOTHING;
    SQL
  end

  def down
    execute "DELETE FROM import_sources WHERE key = 'country_catalog';"
    execute "DROP TABLE IF EXISTS import_country_name_source_links;"
    execute "DROP TABLE IF EXISTS import_country_source_links;"
    execute "DROP INDEX IF EXISTS index_places_on_country_id;"
    execute "ALTER TABLE places DROP COLUMN IF EXISTS country_id;"
    execute "DROP TABLE IF EXISTS country_names;"
    execute "DROP TABLE IF EXISTS countries;"
  end
end
