class CreateImportFoundation < ActiveRecord::Migration[8.1]
  def up
    execute <<~SQL
      CREATE TABLE import_sources (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key text NOT NULL,
        provider_key text NOT NULL,
        dataset_key text NOT NULL,
        target_kind text NOT NULL,
        fetch_mode text NOT NULL,
        enabled boolean NOT NULL DEFAULT TRUE,
        license_key text NOT NULL,
        license_url text,
        attribution_text text,
        config jsonb NOT NULL DEFAULT '{}'::jsonb,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_sources_on_key
      ON import_sources (key);
    SQL

    execute <<~SQL
      CREATE TABLE import_runs (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_id bigint NOT NULL REFERENCES import_sources(id),
        retry_of_run_id bigint REFERENCES import_runs(id),
        initiated_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
        mode text NOT NULL,
        status text NOT NULL,
        params jsonb NOT NULL DEFAULT '{}'::jsonb,
        stats jsonb NOT NULL DEFAULT '{}'::jsonb,
        total_item_count integer NOT NULL DEFAULT 0,
        completed_item_count integer NOT NULL DEFAULT 0,
        failed_item_count integer NOT NULL DEFAULT 0,
        issue_count integer NOT NULL DEFAULT 0,
        started_at timestamptz,
        finished_at timestamptz,
        cancel_requested_at timestamptz,
        error_code text,
        error_message text,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_import_runs_on_source_id ON import_runs (source_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_runs_on_retry_of_run_id ON import_runs (retry_of_run_id);
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_runs_on_source_id_active
      ON import_runs (source_id)
      WHERE status IN ('queued', 'running');
    SQL

    execute <<~SQL
      CREATE TABLE import_run_items (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id bigint NOT NULL REFERENCES import_runs(id),
        item_kind text NOT NULL,
        item_key text NOT NULL,
        status text NOT NULL,
        params jsonb NOT NULL DEFAULT '{}'::jsonb,
        checkpoint jsonb NOT NULL DEFAULT '{}'::jsonb,
        stats jsonb NOT NULL DEFAULT '{}'::jsonb,
        attempts_count integer NOT NULL DEFAULT 0,
        lease_token text,
        lease_expires_at timestamptz,
        started_at timestamptz,
        finished_at timestamptz,
        error_code text,
        error_message text,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_import_run_items_on_run_id ON import_run_items (run_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_run_items_on_status ON import_run_items (status);
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_run_items_on_run_kind_and_key
      ON import_run_items (run_id, item_kind, item_key);
    SQL

    execute <<~SQL
      CREATE TABLE import_artifacts (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id bigint NOT NULL REFERENCES import_runs(id),
        run_item_id bigint REFERENCES import_run_items(id) ON DELETE SET NULL,
        kind text NOT NULL,
        sha256 text NOT NULL,
        byte_size bigint,
        content_type text,
        source_url text,
        metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
        captured_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_import_artifacts_on_run_id ON import_artifacts (run_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_artifacts_on_run_item_id ON import_artifacts (run_item_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_artifacts_on_sha256 ON import_artifacts (sha256);
    SQL

    execute <<~SQL
      CREATE TABLE import_source_records (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_id bigint NOT NULL REFERENCES import_sources(id),
        record_kind text NOT NULL,
        external_uid text NOT NULL,
        status text NOT NULL,
        checksum text NOT NULL,
        raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
        normalized_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
        first_seen_at timestamptz NOT NULL,
        last_seen_at timestamptz NOT NULL,
        last_changed_at timestamptz,
        last_import_run_id bigint REFERENCES import_runs(id) ON DELETE SET NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_source_records_on_identity
      ON import_source_records (source_id, record_kind, external_uid);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_source_records_on_last_import_run_id
      ON import_source_records (last_import_run_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_source_records_on_status
      ON import_source_records (status);
    SQL

    execute <<~SQL
      CREATE TABLE import_record_snapshots (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_record_id bigint NOT NULL REFERENCES import_source_records(id),
        run_id bigint NOT NULL REFERENCES import_runs(id),
        checksum text NOT NULL,
        raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
        normalized_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
        captured_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_import_record_snapshots_on_source_record_id
      ON import_record_snapshots (source_record_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_record_snapshots_on_run_id
      ON import_record_snapshots (run_id);
    SQL

    execute <<~SQL
      CREATE TABLE import_issues (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_id bigint NOT NULL REFERENCES import_runs(id),
        run_item_id bigint REFERENCES import_run_items(id) ON DELETE SET NULL,
        source_record_id bigint REFERENCES import_source_records(id) ON DELETE SET NULL,
        stage text NOT NULL,
        code text NOT NULL,
        severity text NOT NULL,
        status text NOT NULL,
        message text NOT NULL,
        details jsonb NOT NULL DEFAULT '{}'::jsonb,
        row_locator text,
        resolved_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_import_issues_on_run_id ON import_issues (run_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_issues_on_run_item_id ON import_issues (run_item_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_issues_on_source_record_id ON import_issues (source_record_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_issues_on_status ON import_issues (status);
    SQL

    execute <<~SQL
      CREATE TABLE import_airport_source_links (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_record_id bigint NOT NULL REFERENCES import_source_records(id),
        airport_place_id uuid NOT NULL REFERENCES airports(place_id),
        match_strategy text NOT NULL,
        confidence numeric(5,4) NOT NULL,
        matched_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_airport_source_links_on_source_record_id
      ON import_airport_source_links (source_record_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_airport_source_links_on_airport_place_id
      ON import_airport_source_links (airport_place_id);
    SQL

    execute <<~SQL
      CREATE TABLE active_storage_blobs (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key text NOT NULL,
        filename text NOT NULL,
        content_type text,
        metadata text,
        service_name text NOT NULL,
        byte_size bigint NOT NULL,
        checksum text,
        created_at timestamptz NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_active_storage_blobs_on_key
      ON active_storage_blobs (key);
    SQL

    execute <<~SQL
      CREATE TABLE active_storage_attachments (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        record_type text NOT NULL,
        record_id bigint NOT NULL,
        blob_id bigint NOT NULL REFERENCES active_storage_blobs(id),
        created_at timestamptz NOT NULL,
        CONSTRAINT active_storage_attachments_uniqueness
          UNIQUE (record_type, record_id, name)
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_active_storage_attachments_on_blob_id
      ON active_storage_attachments (blob_id);
    SQL

    execute <<~SQL
      INSERT INTO import_sources (
        key,
        provider_key,
        dataset_key,
        target_kind,
        fetch_mode,
        license_key,
        attribution_text
      ) VALUES (
        'ourairports_airports',
        'ourairports',
        'airports',
        'airport',
        'remote_dump',
        'ourairports',
        'OurAirports'
      ) ON CONFLICT (key) DO NOTHING;
    SQL
  end

  def down
    execute "DROP TABLE IF EXISTS active_storage_attachments;"
    execute "DROP TABLE IF EXISTS active_storage_blobs;"
    execute "DROP TABLE IF EXISTS import_airport_source_links;"
    execute "DROP TABLE IF EXISTS import_issues;"
    execute "DROP TABLE IF EXISTS import_record_snapshots;"
    execute "DROP TABLE IF EXISTS import_source_records;"
    execute "DROP TABLE IF EXISTS import_artifacts;"
    execute "DROP TABLE IF EXISTS import_run_items;"
    execute "DROP TABLE IF EXISTS import_runs;"
    execute "DROP TABLE IF EXISTS import_sources;"
  end
end
