class AddAirlineReferenceCatalog < ActiveRecord::Migration[8.1]
  def up
    execute <<~SQL
      CREATE TABLE airlines (
        id uuid PRIMARY KEY DEFAULT uuidv7(),
        name text NOT NULL,
        normalized_name text NOT NULL,
        review_status text NOT NULL,
        operational_status text NOT NULL,
        record_kind text NOT NULL,
        system_key text,
        country_id uuid REFERENCES countries(id),
        merged_into_id uuid REFERENCES airlines(id),
        pending_fingerprint text,
        reviewed_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
        reviewed_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT airlines_merge_target_consistency CHECK (
          (review_status = 'merged' AND merged_into_id IS NOT NULL) OR
          (review_status <> 'merged' AND merged_into_id IS NULL)
        ),
        CONSTRAINT airlines_cannot_merge_into_self CHECK (merged_into_id IS NULL OR merged_into_id <> id)
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_airlines_on_system_key
      ON airlines (system_key)
      WHERE system_key IS NOT NULL;
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_airlines_on_open_pending_fingerprint
      ON airlines (pending_fingerprint)
      WHERE review_status = 'pending' AND pending_fingerprint IS NOT NULL;
    SQL

    execute <<~SQL
      CREATE INDEX index_airlines_on_review_and_normalized_name
      ON airlines (review_status, normalized_name text_pattern_ops);
    SQL

    execute <<~SQL
      CREATE INDEX index_airlines_on_country_id
      ON airlines (country_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_airlines_on_merged_into_id
      ON airlines (merged_into_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_airlines_on_reviewed_by_user_id
      ON airlines (reviewed_by_user_id);
    SQL

    execute <<~SQL
      CREATE TABLE airline_designators (
        id uuid PRIMARY KEY DEFAULT uuidv7(),
        airline_id uuid NOT NULL REFERENCES airlines(id),
        system text NOT NULL,
        code text NOT NULL,
        valid_from date,
        valid_until date,
        controlled_duplicate boolean NOT NULL DEFAULT false,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT airline_designators_validity_order CHECK (
          valid_from IS NULL OR valid_until IS NULL OR valid_from <= valid_until
        ),
        CONSTRAINT airline_designators_airline_system_code_key UNIQUE (airline_id, system, code)
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_airline_designators_on_airline_id
      ON airline_designators (airline_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_airline_designators_on_system_and_code
      ON airline_designators (system, code);
    SQL

    execute <<~SQL
      CREATE TABLE airline_submissions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        airline_id uuid NOT NULL REFERENCES airlines(id),
        submitted_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
        submitted_name text NOT NULL,
        submitted_code text,
        submitted_country_id uuid REFERENCES countries(id),
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT airline_submissions_airline_id_key UNIQUE (airline_id)
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_airline_submissions_on_submitted_by_user_id
      ON airline_submissions (submitted_by_user_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_airline_submissions_on_submitted_country_id
      ON airline_submissions (submitted_country_id);
    SQL

    execute <<~SQL
      CREATE TABLE import_airline_source_links (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_record_id bigint NOT NULL REFERENCES import_source_records(id),
        airline_id uuid NOT NULL REFERENCES airlines(id),
        match_strategy text NOT NULL,
        matched_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_import_airline_source_links_on_source_record_id
      ON import_airline_source_links (source_record_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_import_airline_source_links_on_airline_id
      ON import_airline_source_links (airline_id);
    SQL
  end

  def down
    execute "DROP TABLE IF EXISTS import_airline_source_links;"
    execute "DROP TABLE IF EXISTS airline_submissions;"
    execute "DROP TABLE IF EXISTS airline_designators;"
    execute "DROP TABLE IF EXISTS airlines;"
  end
end
