class CreateSolidQueueSchema < ActiveRecord::Migration[8.1]
  def up
    execute <<~SQL
      CREATE TABLE solid_queue_jobs (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        queue_name character varying NOT NULL,
        class_name character varying NOT NULL,
        arguments text,
        priority integer NOT NULL DEFAULT 0,
        active_job_id character varying,
        scheduled_at timestamp(6),
        finished_at timestamp(6),
        concurrency_key character varying,
        created_at timestamp(6) NOT NULL,
        updated_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_jobs_on_active_job_id
        ON solid_queue_jobs (active_job_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_jobs_on_class_name
        ON solid_queue_jobs (class_name);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_jobs_on_finished_at
        ON solid_queue_jobs (finished_at);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_jobs_for_filtering
        ON solid_queue_jobs (queue_name, finished_at);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_jobs_for_alerting
        ON solid_queue_jobs (scheduled_at, finished_at);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_blocked_executions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id bigint NOT NULL,
        queue_name character varying NOT NULL,
        priority integer NOT NULL DEFAULT 0,
        concurrency_key character varying NOT NULL,
        expires_at timestamp(6) NOT NULL,
        created_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_blocked_executions_for_release
        ON solid_queue_blocked_executions (concurrency_key, priority, job_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_blocked_executions_for_maintenance
        ON solid_queue_blocked_executions (expires_at, concurrency_key);
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_blocked_executions_on_job_id
        ON solid_queue_blocked_executions (job_id);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_claimed_executions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id bigint NOT NULL,
        process_id bigint,
        created_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_claimed_executions_on_job_id
        ON solid_queue_claimed_executions (job_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_claimed_executions_on_process_id_and_job_id
        ON solid_queue_claimed_executions (process_id, job_id);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_failed_executions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id bigint NOT NULL,
        error text,
        created_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_failed_executions_on_job_id
        ON solid_queue_failed_executions (job_id);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_pauses (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        queue_name character varying NOT NULL,
        created_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_pauses_on_queue_name
        ON solid_queue_pauses (queue_name);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_processes (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kind character varying NOT NULL,
        last_heartbeat_at timestamp(6) NOT NULL,
        supervisor_id bigint,
        pid integer NOT NULL,
        hostname character varying,
        metadata text,
        created_at timestamp(6) NOT NULL,
        name character varying NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_processes_on_last_heartbeat_at
        ON solid_queue_processes (last_heartbeat_at);
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_processes_on_name_and_supervisor_id
        ON solid_queue_processes (name, supervisor_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_processes_on_supervisor_id
        ON solid_queue_processes (supervisor_id);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_ready_executions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id bigint NOT NULL,
        queue_name character varying NOT NULL,
        priority integer NOT NULL DEFAULT 0,
        created_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_ready_executions_on_job_id
        ON solid_queue_ready_executions (job_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_poll_all
        ON solid_queue_ready_executions (priority, job_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_poll_by_queue
        ON solid_queue_ready_executions (queue_name, priority, job_id);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_recurring_tasks (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key character varying NOT NULL,
        schedule character varying NOT NULL,
        command character varying(2048),
        class_name character varying,
        arguments text,
        queue_name character varying,
        priority integer DEFAULT 0,
        static boolean NOT NULL DEFAULT TRUE,
        description text,
        created_at timestamp(6) NOT NULL,
        updated_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_recurring_tasks_on_key
        ON solid_queue_recurring_tasks (key);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_recurring_tasks_on_static
        ON solid_queue_recurring_tasks (static);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_recurring_executions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id bigint NOT NULL,
        task_key character varying NOT NULL,
        run_at timestamp(6) NOT NULL,
        created_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_recurring_executions_on_job_id
        ON solid_queue_recurring_executions (job_id);
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_recurring_executions_on_task_key_and_run_at
        ON solid_queue_recurring_executions (task_key, run_at);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_scheduled_executions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id bigint NOT NULL,
        queue_name character varying NOT NULL,
        priority integer NOT NULL DEFAULT 0,
        scheduled_at timestamp(6) NOT NULL,
        created_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_scheduled_executions_on_job_id
        ON solid_queue_scheduled_executions (job_id);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_dispatch_all
        ON solid_queue_scheduled_executions (scheduled_at, priority, job_id);
    SQL

    execute <<~SQL
      CREATE TABLE solid_queue_semaphores (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key character varying NOT NULL,
        value integer NOT NULL DEFAULT 1,
        expires_at timestamp(6) NOT NULL,
        created_at timestamp(6) NOT NULL,
        updated_at timestamp(6) NOT NULL
      );
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_semaphores_on_expires_at
        ON solid_queue_semaphores (expires_at);
    SQL

    execute <<~SQL
      CREATE INDEX index_solid_queue_semaphores_on_key_and_value
        ON solid_queue_semaphores (key, value);
    SQL

    execute <<~SQL
      CREATE UNIQUE INDEX index_solid_queue_semaphores_on_key
        ON solid_queue_semaphores (key);
    SQL

    execute <<~SQL
      ALTER TABLE solid_queue_blocked_executions
        ADD CONSTRAINT fk_rails_4cd34e2228
        FOREIGN KEY (job_id) REFERENCES solid_queue_jobs (id) ON DELETE CASCADE;
    SQL

    execute <<~SQL
      ALTER TABLE solid_queue_claimed_executions
        ADD CONSTRAINT fk_rails_9cfe4d4944
        FOREIGN KEY (job_id) REFERENCES solid_queue_jobs (id) ON DELETE CASCADE;
    SQL

    execute <<~SQL
      ALTER TABLE solid_queue_failed_executions
        ADD CONSTRAINT fk_rails_39bbc7a631
        FOREIGN KEY (job_id) REFERENCES solid_queue_jobs (id) ON DELETE CASCADE;
    SQL

    execute <<~SQL
      ALTER TABLE solid_queue_ready_executions
        ADD CONSTRAINT fk_rails_81fcbd66af
        FOREIGN KEY (job_id) REFERENCES solid_queue_jobs (id) ON DELETE CASCADE;
    SQL

    execute <<~SQL
      ALTER TABLE solid_queue_recurring_executions
        ADD CONSTRAINT fk_rails_318a5533ed
        FOREIGN KEY (job_id) REFERENCES solid_queue_jobs (id) ON DELETE CASCADE;
    SQL

    execute <<~SQL
      ALTER TABLE solid_queue_scheduled_executions
        ADD CONSTRAINT fk_rails_c4316f352d
        FOREIGN KEY (job_id) REFERENCES solid_queue_jobs (id) ON DELETE CASCADE;
    SQL
  end

  def down
    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_blocked_executions;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_claimed_executions;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_failed_executions;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_pauses;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_processes;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_ready_executions;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_recurring_executions;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_recurring_tasks;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_scheduled_executions;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_semaphores;
    SQL

    execute <<~SQL
      DROP TABLE IF EXISTS solid_queue_jobs;
    SQL
  end
end
